//配置小球与线条信息
		var config = {
			//小球数量
			Number:100,
			//小球半径
			Radius:10,
			//小球横向速度范围
			spotSpeedX:1,
			//小球纵向速度范围
			spotSpeedY:1,
			//小球覆盖样式:"lighter"颜色叠加,"xor"覆盖区域显示白色
			globalCompositeOperation:"lighter",
			//小球透明度
			globalAlpha:0.5,
			//线条颜色
			lineColor:"silver",
			//线条粗细
			lineWeight:1,
			//线条连接范围
			Range:300,
			//线条两端样式:"round"圆角,"square"方角
			lineCap:"round"
		}